In [4]:
import pandas as pd
import numpy as np
import os

print(os.getcwd())

/Users/nicholasmessere/Desktop/developer-test-6078Y-main/part_a/data

In [7]:

expression_data = pd.read_csv('icb_gene_expression.csv')
clinical_data = pd.read_csv('icb_clinical_data.csv')
expression_data

,Unnamed: 0,P5,P7,P9,P10,P16,P17,P18,P26,P28,P29
0,ENSG00000000003.15,7.765452,8.913429,9.771778,9.273033,9.772394,7.824535,8.591114,9.148168,8.489485,8.648398
1,ENSG00000000005.6,3.204887,-9.965784,-9.965784,2.902536,3.521746,-9.965784,3.618535,-9.965784,3.675813,1.948329
2,ENSG00000000419.14,10.467766,11.175347,10.750276,11.111797,10.456492,10.524970,10.105455,10.895234,10.295921,10.610446
3,ENSG00000000457.14,8.548142,7.936986,8.980694,8.732069,8.699541,8.679584,8.671533,9.848007,9.015553,8.450990
4,ENSG00000000460.17,9.433551,7.942815,8.777460,8.640439,9.046752,8.146462,8.549159,9.823800,9.245558,8.613295
5,ENSG00000000938.13,6.765458,6.808805,7.656306,7.092178,6.683522,8.423571,7.090916,8.163683,6.641499,8.336838
6,ENSG00000000971.17,15.353715,14.921520,13.575264,15.074575,12.631190,15.338373,12.880043,15.340231,14.705634,14.611246
7,ENSG00000001036.14,9.734553,10.304896,11.173952,9.977824,9.908777,8.679584,9.739435,9.878880,9.990851,9.982480
8,ENSG00000001084.13,9.654293,11.280360,11.201149,10.058428,10.733509,10.478534,11.084393,9.517653,11.079778,10.143697
9,ENSG00000001167.15,9.600480,8.367996,9.614073,8.290365,9.094512,8.619713,9.488785,8.000494,10.072306,9.256296

In [6]:
clinical_data

,Unnamed: 0,patientid,sex,age,cancer_type,histo,tissueid,treatmentid,stage,response.other.info,recist
0,P10,P10,M,55.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PD
1,P16,P16,F,60.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PD
2,P17,P17,M,65.0,Kidney,NaN,Kidney,NaN,NaN,NaN,mixed
3,P18,P18,M,68.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PR
4,P26,P26,F,75.0,Kidney,NaN,Kidney,NaN,NaN,NaN,mixed
5,P28,P28,F,80.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PD
6,P29,P29,F,85.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PR
7,P31,P31,M,88.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PR
8,P36,P36,F,20.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PD
9,P42,P42,M,40.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PR
10,P5,P5,F,48.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PD
11,P55,P55,F,56.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PD
12,P61,P61,F,67.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PR
13,P7,P7,M,58.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PR
14,P9,P9,M,33.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PD
15,NaN,NaN,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NA.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NA.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NA.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NA.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
expr_sample_ids = set(expression_data.columns[1:])


# Get patient IDs from clinical dataset
clin_sample_ids = set(clinical_data["patientid"])

# Find columns in expression but not in clinical
missing_in_clinical = clin_sample_ids - expr_sample_ids

print(missing_in_clinical)

{nan, 'P31', 'P42', 'P55', 'P61', 'P36'}

In [19]:
# Count missing values in each clinical dataset column
missing_clinical_cols = clinical_data.isna().sum()

# Calculate percentage missing for each sample (row) in clinical data
missing_per_sample = clinical_data.isna().mean(axis=1) * 100

# Flag samples with more than 10% missing fields
flagged_samples = clinical_data.loc[missing_per_sample > 10, "patientid"]
print("\nMissing values per clinical column:")
print(missing_clinical_cols)
print("\nSamples with >10% missing clinical fields:")
print(flagged_samples.tolist())

Missing values per clinical column:
Unnamed: 0              1
patientid               5
sex                     4
age                     5
cancer_type             5
histo                  20
tissueid                5
treatmentid            20
stage                  20
response.other.info    20
recist                  5
dtype: int64

Samples with >10% missing clinical fields:
['P10', 'P16', 'P17', 'P18', 'P26', 'P28', 'P29', 'P31', 'P36', 'P42', 'P5', 'P55', 'P61', 'P7', 'P9', nan, nan, nan, nan, nan]

In [25]:
# Calculate mean expression for each gene (skip first column which is gene ID)
expression_data["mean_expression"] = expression_data.iloc[:, 1:].mean(axis=1)

# Sort by mean expression (descending) and select top 5
top5_genes = expression_data.sort_values(by="mean_expression", ascending=False).head(5)

# Output
top5_genes[["Unnamed: 0", "mean_expression"]].to_csv("top5_genes.csv")
print(top5_genes[["Unnamed: 0", "mean_expression"]])

           Unnamed: 0  mean_expression
6  ENSG00000000971.17        14.443179
2  ENSG00000000419.14        10.639370
8  ENSG00000001084.13        10.523179
7  ENSG00000001036.14         9.937123
9  ENSG00000001167.15         9.040502

In [24]:
import pandas as pd

# Load datasets
expr_df = pd.read_csv("icb_gene_expression.csv")
clin_df = pd.read_csv("icb_clinical_data.csv")

# Get the list of common sample IDs
expr_sample_ids = set(expression_data.columns[1:])
clin_sample_ids = set(clinical_data["patientid"])
common_ids = sorted(expr_sample_ids & clin_sample_ids)

# Subset expression data to keep only common IDs
expr_common = expr_df[["Unnamed: 0"] + common_ids]

# Transpose expression data so samples become rows and gene IDs are columns
expr_common_t = expr_common.set_index("Unnamed: 0").T
expr_common_t.index.name = "patientid"

# Merge with clinical data on patientid
merged_df = pd.merge(expr_common_t.reset_index(), clin_df, on="patientid", how="inner")

print(merged_df.shape)
merged_df.to_csv("merged_data.csv")
merged_df.head()

(10, 21)

,patientid,ENSG00000000003.15,ENSG00000000005.6,ENSG00000000419.14,ENSG00000000457.14,ENSG00000000460.17,ENSG00000000938.13,ENSG00000000971.17,ENSG00000001036.14,ENSG00000001084.13,...,Unnamed: 0,sex,age,cancer_type,histo,tissueid,treatmentid,stage,response.other.info,recist
0,P10,9.273033,2.902536,11.111797,8.732069,8.640439,7.092178,15.074575,9.977824,10.058428,...,P10,M,55.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PD
1,P16,9.772394,3.521746,10.456492,8.699541,9.046752,6.683522,12.631190,9.908777,10.733509,...,P16,F,60.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PD
2,P17,7.824535,-9.965784,10.524970,8.679584,8.146462,8.423571,15.338373,8.679584,10.478534,...,P17,M,65.0,Kidney,NaN,Kidney,NaN,NaN,NaN,mixed
3,P18,8.591114,3.618535,10.105455,8.671533,8.549159,7.090916,12.880043,9.739435,11.084393,...,P18,M,68.0,Kidney,NaN,Kidney,NaN,NaN,NaN,PR
4,P26,9.148168,-9.965784,10.895234,9.848007,9.823800,8.163683,15.340231,9.878880,9.517653,...,P26,F,75.0,Kidney,NaN,Kidney,NaN,NaN,NaN,mixed